import React, { useState } from 'react';
import { ShieldAlert, Zap, AlertTriangle, CheckCircle2, Code, Play, X, Copy, Check, Info, ShieldCheck, Activity } from 'lucide-react';
import SpotlightCard from './bits/SpotlightCard';
import AnimatedCounter from './bits/AnimatedCounter';

export default function AuditPanel() {
  const [activeFixModal, setActiveFixModal] = useState(null);
  const [copied, setCopied] = useState(false);
  const [appliedFixes, setAppliedFixes] = useState([]);

  const findings = [
    {
      id: 1,
      severity: 'CRITICAL',
      type: 'UNINDEXED_FOREIGN_KEY',
      title: 'Unindexed foreign key in order_items.order_id',
      affectedTable: 'order_items',
      affectedColumn: 'order_id',
      impact: 'High latency (450ms) on joined queries across 98.4K rows.',
      recommendation: 'Create composite index on order_items(order_id, product_id).',
      estimatedGain: '4.8x speedup',
      fixSql: `-- Migration script generated by SchemaStudio
CREATE INDEX CONCURRENTLY idx_order_items_order_id ON order_items(order_id, product_id);
COMMENT ON INDEX idx_order_items_order_id IS 'Optimizes join performance between orders and order_items';`
    },
    {
      id: 2,
      severity: 'WARNING',
      type: 'MISSING_INDEX',
      title: 'Unindexed category FK in products.category_id',
      affectedTable: 'products',
      affectedColumn: 'category_id',
      impact: 'Sequential scans across 3.4K rows when filtering catalog by category.',
      recommendation: 'Create single column index on products(category_id).',
      estimatedGain: '2.1x speedup',
      fixSql: `-- Migration script generated by SchemaStudio
CREATE INDEX CONCURRENTLY idx_products_category_id ON products(category_id);`
    },
    {
      id: 3,
      severity: 'INFORMATIONAL',
      type: 'CONSTRAINT_CHECK',
      title: 'Explicit cascade rule omitted on order_items FK',
      affectedTable: 'order_items',
      affectedColumn: 'order_id',
      impact: 'Potential for orphaned records if an order is deleted directly.',
      recommendation: 'Add explicit ON DELETE CASCADE constraint.',
      estimatedGain: 'Integrity',
      fixSql: `-- Migration script generated by SchemaStudio
ALTER TABLE order_items DROP CONSTRAINT IF EXISTS fk_order_items_orders;
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;`
    }
  ];

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleConfirmFix = (id) => {
    setAppliedFixes((prev) => [...prev, id]);
    setActiveFixModal(null);
  };

  return (
    <div className="space-y-4 font-sans">
      {/* Overview & Score Card */}
      <SpotlightCard className="p-4 rounded-md border border-[#DDE0DA] bg-white">
        <div className="grid grid-cols-12 gap-4 items-center">
          <div className="col-span-5 flex items-center gap-3 border-r border-[#DDE0DA] pr-4">
            <div className="w-12 h-12 rounded-sm bg-[#EEF2FF] border border-[#C7D2FE] flex items-center justify-center text-[#2454FF] font-mono text-xl font-bold">
              <AnimatedCounter value={82} />
            </div>
            <div>
              <div className="text-[11px] font-mono text-[#2454FF] font-semibold">Database health score</div>
              <h2 className="text-lg font-mono font-bold text-[#15181D] tabular-nums">
                <AnimatedCounter value={82} suffix=" / 100" />
              </h2>
              <p className="text-[11px] font-mono text-[#7A8087]">
                Last audit: <span className="text-[#15181D] font-mono tabular-nums">2026-09-22 22:45 UTC</span>
              </p>
            </div>
          </div>

          <div className="col-span-7 grid grid-cols-3 gap-2.5 font-mono text-xs">
            <div className="bg-[#F5F6F2] p-2.5 rounded-sm border border-[#DDE0DA] space-y-0.5">
              <div className="text-[#7A8087] text-[10px] flex items-center gap-1 font-medium">
                <Zap className="w-3.5 h-3.5 text-[#2454FF]" />
                <span>Performance</span>
              </div>
              <div className="text-sm font-bold text-[#2454FF] tabular-nums"><AnimatedCounter value={76} suffix=" / 100" /></div>
              <div className="text-[10px] text-[#7A8087] tabular-nums">2 slow queries</div>
            </div>

            <div className="bg-[#F5F6F2] p-2.5 rounded-sm border border-[#DDE0DA] space-y-0.5">
              <div className="text-[#7A8087] text-[10px] flex items-center gap-1 font-medium">
                <ShieldCheck className="w-3.5 h-3.5 text-[#159F6B]" />
                <span>Security</span>
              </div>
              <div className="text-sm font-bold text-[#159F6B] tabular-nums"><AnimatedCounter value={92} suffix=" / 100" /></div>
              <div className="text-[10px] text-[#7A8087] tabular-nums">0 exposed secrets</div>
            </div>

            <div className="bg-[#F5F6F2] p-2.5 rounded-sm border border-[#DDE0DA] space-y-0.5">
              <div className="text-[#7A8087] text-[10px] flex items-center gap-1 font-medium">
                <Activity className="w-3.5 h-3.5 text-[#C2790A]" />
                <span>Index coverage</span>
              </div>
              <div className="text-sm font-bold text-[#C2790A] tabular-nums"><AnimatedCounter value={78} suffix="%" /></div>
              <div className="text-[10px] text-[#7A8087] tabular-nums">2 missing indexes</div>
            </div>
          </div>
        </div>
      </SpotlightCard>

      {/* Findings Grouped by Severity */}
      <div className="space-y-2.5">
        <div className="flex items-center justify-between text-xs font-mono text-[#7A8087]">
          <span className="font-semibold text-[#15181D]">Audit findings ({findings.length})</span>
          <span className="tabular-nums">Applied fixes: {appliedFixes.length} / {findings.length}</span>
        </div>

        {findings.map((finding) => {
          const isFixed = appliedFixes.includes(finding.id);
          return (
            <SpotlightCard
              key={finding.id}
              className={`p-4 space-y-2.5 transition-all rounded-sm ${
                isFixed ? 'border-[#A3E3C9] bg-[#E8F8F2]' : 'border-[#DDE0DA] bg-white'
              }`}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span
                    className={`text-[10px] font-mono font-semibold px-2 py-0.5 rounded-sm border ${
                      finding.severity === 'CRITICAL'
                        ? 'bg-[#FDF2F4] text-[#D0334C] border-[#F6BAC4]'
                        : finding.severity === 'WARNING'
                        ? 'bg-[#FEF8EE] text-[#C2790A] border-[#FBE0AD]'
                        : 'bg-[#EEF2FF] text-[#2454FF] border-[#C7D2FE]'
                    }`}
                  >
                    {finding.severity}
                  </span>
                  <h4 className="font-heading text-xs font-bold text-[#15181D]">{finding.title}</h4>
                </div>

                {isFixed ? (
                  <span className="text-xs font-mono text-[#159F6B] font-semibold flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5 text-[#159F6B]" /> Fix applied
                  </span>
                ) : (
                  <button
                    onClick={() => setActiveFixModal(finding)}
                    className="px-3 py-1 rounded-sm bg-[#2454FF] text-white font-semibold text-xs flex items-center gap-1 hover:bg-[#1D44D8] transition-all"
                  >
                    <Play className="w-3.5 h-3.5" /> Apply fix
                  </button>
                )}
              </div>

              <div className="grid grid-cols-3 gap-2.5 font-mono text-xs text-[#4B5157]">
                <div>
                  <span className="text-[10px] text-[#7A8087] block">Location:</span>
                  <div className="text-[#2454FF] font-semibold mt-0.5">{finding.affectedTable}.{finding.affectedColumn}</div>
                </div>
                <div>
                  <span className="text-[10px] text-[#7A8087] block">Impact:</span>
                  <div className="text-[#353A40] mt-0.5 font-sans">{finding.impact}</div>
                </div>
                <div>
                  <span className="text-[10px] text-[#7A8087] block">Estimated gain:</span>
                  <div className="text-[#159F6B] font-bold mt-0.5 tabular-nums">{finding.estimatedGain}</div>
                </div>
              </div>
            </SpotlightCard>
          );
        })}
      </div>

      {/* AI FIX CONFIRMATION MODAL */}
      {activeFixModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#15181D]/30 backdrop-blur-xs font-sans">
          <div className="w-full max-w-lg bg-white rounded-md p-5 border border-[#DDE0DA] shadow-lg space-y-3 corner-tick">
            <div className="flex items-center justify-between border-b border-[#DDE0DA] pb-2.5">
              <div className="flex items-center gap-2 text-[#2454FF] font-semibold text-xs">
                <Code className="w-4 h-4 text-[#2454FF]" /> Confirm migration fix script
              </div>
              <button onClick={() => setActiveFixModal(null)} className="text-[#7A8087] hover:text-[#15181D]">
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="space-y-2 font-mono text-xs">
              <div className="text-[#15181D] font-bold font-heading">{activeFixModal.title}</div>
              <div className="text-[#7A8087]">Target Table: <span className="text-[#2454FF]">{activeFixModal.affectedTable}</span></div>

              <div className="pt-1">
                <div className="flex items-center justify-between text-[#7A8087] text-[10px] mb-1">
                  <span>SQL migration script:</span>
                  <button
                    onClick={() => handleCopy(activeFixModal.fixSql)}
                    className="text-[#2454FF] hover:underline flex items-center gap-1"
                  >
                    {copied ? <Check className="w-3 h-3 text-[#159F6B]" /> : <Copy className="w-3 h-3" />}
                    <span>{copied ? 'Copied' : 'Copy script'}</span>
                  </button>
                </div>
                <pre className="bg-[#15181D] p-3 rounded-sm border border-[#353A40] text-[#159F6B] text-xs overflow-x-auto">
                  {activeFixModal.fixSql}
                </pre>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-[#DDE0DA]">
              <button
                onClick={() => setActiveFixModal(null)}
                className="px-3 py-1.5 rounded-sm border border-[#DDE0DA] text-[#4B5157] text-xs hover:border-[#C3C8BF]"
              >
                Cancel
              </button>
              <button
                onClick={() => handleConfirmFix(activeFixModal.id)}
                className="px-3.5 py-1.5 rounded-sm bg-[#2454FF] text-white font-semibold text-xs flex items-center gap-1 hover:bg-[#1D44D8]"
              >
                <CheckCircle2 className="w-3.5 h-3.5" /> Execute fix
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
