import React, { useState } from 'react';
import { Code2, Download, Copy, Check, FileCode, Layers, Terminal } from 'lucide-react';
import SpotlightCard from './bits/SpotlightCard';

export default function CodeExporter() {
  const [activeTarget, setActiveTarget] = useState('PRISMA');
  const [activePreset, setActivePreset] = useState('ECOMMERCE');
  const [copied, setCopied] = useState(false);

  const presets = {
    ECOMMERCE: [
      { name: 'User', table: 'users', fields: [{ name: 'id', type: 'String', isPk: true }, { name: 'email', type: 'String', unique: true }, { name: 'role', type: 'Role' }] },
      { name: 'Product', table: 'products', fields: [{ name: 'id', type: 'String', isPk: true }, { name: 'title', type: 'String' }, { name: 'price', type: 'Float' }, { name: 'stockQty', type: 'Int' }] },
      { name: 'Order', table: 'orders', fields: [{ name: 'id', type: 'String', isPk: true }, { name: 'userId', type: 'String' }, { name: 'totalAmount', type: 'Float' }, { name: 'status', type: 'OrderStatus' }] }
    ],
    SAAS: [
      { name: 'Organization', table: 'organizations', fields: [{ name: 'id', type: 'String', isPk: true }, { name: 'name', type: 'String' }, { name: 'planTier', type: 'String' }] },
      { name: 'User', table: 'users', fields: [{ name: 'id', type: 'String', isPk: true }, { name: 'orgId', type: 'String' }, { name: 'email', type: 'String' }] }
    ]
  };

  const currentModels = presets[activePreset] || presets.ECOMMERCE;

  const generatePrisma = () => {
    let code = `// Prisma Schema generated by SchemaStudio Architect\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\n`;
    currentModels.forEach((m) => {
      code += `model ${m.name} {\n`;
      m.fields.forEach((f) => {
        const pkAttr = f.isPk ? ' @id @default(uuid())' : '';
        const uniqueAttr = f.unique ? ' @unique' : '';
        code += `  ${f.name.padEnd(15)} ${f.type}${pkAttr}${uniqueAttr}\n`;
      });
      code += `  createdAt       DateTime @default(now())\n`;
      code += `  updatedAt       DateTime @updatedAt\n`;
      code += `}\n\n`;
    });
    return code;
  };

  const generateTypeORM = () => {
    let code = `// TypeORM Entity Definitions generated by SchemaStudio\nimport { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';\n\n`;
    currentModels.forEach((m) => {
      code += `@Entity('${m.table}')\nexport class ${m.name} {\n`;
      m.fields.forEach((f) => {
        if (f.isPk) {
          code += `  @PrimaryGeneratedColumn('uuid')\n  ${f.name}: string;\n\n`;
        } else {
          code += `  @Column({ unique: ${!!f.unique} })\n  ${f.name}: ${f.type.toLowerCase() === 'float' || f.type.toLowerCase() === 'int' ? 'number' : 'string'};\n\n`;
        }
      });
      code += `  @CreateDateColumn()\n  createdAt: Date;\n\n`;
      code += `  @UpdateDateColumn()\n  updatedAt: Date;\n}\n\n`;
    });
    return code;
  };

  const generateGraphQL = () => {
    let code = `# GraphQL Schema Definition generated by SchemaStudio\n\n`;
    currentModels.forEach((m) => {
      code += `type ${m.name} {\n`;
      m.fields.forEach((f) => {
        const gqlType = f.isPk ? 'ID!' : f.type === 'Int' ? 'Int!' : f.type === 'Float' ? 'Float!' : 'String!';
        code += `  ${f.name}: ${gqlType}\n`;
      });
      code += `  createdAt: String!\n`;
      code += `  updatedAt: String!\n`;
      code += `}\n\n`;
    });
    return code;
  };

  const generateDbml = () => {
    let code = `// DBML Database Markup Language generated by SchemaStudio\n\n`;
    currentModels.forEach((m) => {
      code += `Table ${m.table} {\n`;
      m.fields.forEach((f) => {
        const note = f.isPk ? ' [pk]' : f.unique ? ' [unique]' : '';
        code += `  ${f.name} ${f.type}${note}\n`;
      });
      code += `  created_at timestamp\n`;
      code += `}\n\n`;
    });
    return code;
  };

  const getGeneratedCode = () => {
    if (activeTarget === 'PRISMA') return generatePrisma();
    if (activeTarget === 'TYPEORM') return generateTypeORM();
    if (activeTarget === 'GRAPHQL') return generateGraphQL();
    if (activeTarget === 'DBML') return generateDbml();
    return generatePrisma();
  };

  const getFileExtension = () => {
    if (activeTarget === 'PRISMA') return 'schema.prisma';
    if (activeTarget === 'TYPEORM') return 'entities.ts';
    if (activeTarget === 'GRAPHQL') return 'schema.graphql';
    if (activeTarget === 'DBML') return 'database.dbml';
    return 'schema.txt';
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getGeneratedCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([getGeneratedCode()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFileExtension();
    a.click();
  };

  return (
    <div className="space-y-4 font-sans">
      {/* Top Banner */}
      <SpotlightCard className="p-4 rounded-md border border-[#DDE0DA] bg-white space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-sm bg-[#2454FF] text-white flex items-center justify-center font-bold">
              <Code2 className="w-3.5 h-3.5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-[#15181D] font-heading">Multi-ORM & code exporter</h2>
              <p className="text-xs text-[#4B5157]">
                Generate production ORM definitions, GraphQL SDL schemas, and DBML scripts from active schemas.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 text-xs font-mono">
            <button
              onClick={handleCopy}
              className="px-2.5 py-1 rounded-sm bg-[#F5F6F2] border border-[#DDE0DA] text-[#4B5157] hover:text-[#15181D] hover:border-[#C3C8BF] transition-all flex items-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-[#159F6B]" /> : <Copy className="w-3.5 h-3.5 text-[#2454FF]" />}
              <span>{copied ? 'Copied' : 'Copy code'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1 rounded-sm bg-[#2454FF] text-white font-semibold text-xs flex items-center gap-1.5 hover:bg-[#1D44D8] transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download {getFileExtension()}</span>
            </button>
          </div>
        </div>

        {/* Target Format Selector */}
        <div className="flex items-center gap-1 bg-[#F5F6F2] p-1 rounded-sm border border-[#DDE0DA] font-mono text-xs">
          {['PRISMA', 'TYPEORM', 'GRAPHQL', 'DBML'].map((fmt) => (
            <button
              key={fmt}
              onClick={() => setActiveTarget(fmt)}
              className={`px-3 py-1 rounded-sm text-xs transition-all ${
                activeTarget === fmt
                  ? 'bg-white text-[#2454FF] font-semibold border border-[#DDE0DA] corner-tick'
                  : 'text-[#4B5157] hover:text-[#15181D]'
              }`}
            >
              {fmt}
            </button>
          ))}
        </div>
      </SpotlightCard>

      {/* Generated Code Output */}
      <div className="surface-card p-4 rounded-md border border-[#DDE0DA] space-y-3 bg-white">
        <div className="flex items-center justify-between border-b border-[#DDE0DA] pb-2 font-mono text-xs">
          <span className="font-semibold text-[#15181D] flex items-center gap-1.5">
            <Terminal className="w-3.5 h-3.5 text-[#2454FF]" />
            <span>Target: {getFileExtension()}</span>
          </span>
          <span className="text-[10px] text-[#7A8087]">Auto-generated spec</span>
        </div>

        <pre className="bg-[#15181D] p-3.5 rounded-sm border border-[#353A40] text-[#159F6B] text-xs font-mono overflow-x-auto">
          {getGeneratedCode()}
        </pre>
      </div>
    </div>
  );
}
